version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - apt-get update && apt-get install -y unzip git
      - echo "Installing HashiCorp Packer..."
      - rm -rf packer* && curl -qL -o packer.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip && unzip packer.zip
      - echo "Installing jq..."
      - rm -rf jq* && curl -qL -o jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x ./jq
      - ./jq --version
      - echo "Downloading template..."
      - git clone --depth 1 https://github.com/ohsawa0515/ecs-gpu-optimized-ami-auto-update.git
      - mv ecs-gpu-optimized-ami-auto-update/packer_template.json ./
      - echo "Validating template..."
      - ./packer validate packer_template.json
  build:
    commands:
      - ./packer build packer_template.json | tee output.txt
      - ami_id=$(tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }')
      - if [ -z "${ami_id}" ]; then echo 'Faild to create AMI.'; exit 1; fi
      - echo "AMI ID ${ami_id}"
  post_build:
    commands:
      - if [ -z "${ami_id}" ]; then echo "Completed build by HashiCorp Packer."; fi
